root: true
env:
  browser: true
  node: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  parser: '@typescript-eslint/parser'
  project: tsconfig.json
  tsconfigRootDir: ./
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len:
    - warn
    - code: 300
  no-console: 'off'
  no-extra-boolean-cast: warn
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/restrict-plus-operands': warn
  '@typescript-eslint/explicit-module-boundary-types': warn
  '@typescript-eslint/no-floating-promises': warn
  '@typescript-eslint/no-unsafe-member-access': warn
  '@typescript-eslint/no-unsafe-assignment': warn
